name: Build and publish docs

permissions:
  contents: write

on:
  push:
    branches:
      - '**'

jobs:
  build-and-publish-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install --with docs
    - name: Build docs
      run: |
        poetry run pdoc src/wristpy -o docs_build -t docs/pdoc-theme --docformat google
        poetry run pdoc docs/ -o docs_build -t docs/pdoc-theme --docformat google --pages
        touch docs_build/.nojekyll
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs_build
