name: Build and publish docs

permissions:
  contents: write

on:
  push:
    branches:
    - feature/issue-218/sphinx
    - main
  workflow_dispatch:

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fetch LFS files
      run: git lfs pull
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install --with docs
    - name: Build Sphinx docs
      working-directory: docs
      run: |
        poetry run make html
        touch build/html/.nojekyll
        ls -la build/html | sed 's/^/BUILD: /'
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/build/html
        clean: true
        single-commit: true
