name: Build and publish docs

permissions:
  contents: write

on:
  workflow_run:
    workflows: [Python Tests]
    types:
      - completed
    branches:
      - main
      - feature/issue-218/sphinx
  push:
    branches:
      - feature/issue-218/sphinx
  workflow_dispatch:

jobs:
  build-and-publish-docs:
    if: >
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success') ||
      (github.event_name != 'workflow_run')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch LFS files
        run: git lfs pull

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install --with docs

      - name: Build Sphinx docs
        run: |
          cd docs
          poetry run make html
          touch build/html/.nojekyll

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build/html
          clean: true
