name: Build and publish docs

permissions:
  contents: write

on:
  workflow_run:
    workflows: [Python Tests]
    types:
    - completed
    branches:
    - main

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install --with docs
    - name: Build docs
      run: |
        poetry run pdoc src/wristpy -o docs_build -t docs/pdoc-theme --docformat google
        touch docs_build/.nojekyll
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs_build
